# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build storybook

on:
  push:
    branches: [ master ]
    paths:
      - "packages/core"
      - "packages/stories"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn compile
    - run: yarn storybook:build-storybook
    - name: Storybook 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: packages/stories/storybook-static # The folder that the build-storybook script generates files.
        CLEAN: true # Automatically remove deleted files from the deploy branch
        TARGET_FOLDER: docs # The folder that we serve our Storybook files from
